import type { Metadata } from "next";
import { Philosopher, Artifika } from "next/font/google";
import "./globals.css";
import BackgroundPattern from "@/components/common/BackgroundPattern";
import { SidebarWrapper } from "@/components/sidebar/SidebarWrapper";
import { Header } from "@/components/header/header";

const philosopher = Philosopher({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--display-family",
});

const artifika = Artifika({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--text-family",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${philosopher.variable} ${artifika.variable} ${artifika.className} antialiased overflow-x-hidden max-w-7xl mx-auto px-4`}
      >
        <BackgroundPattern />
        <Header href={"/"} type={"Login"} />
        <div className="flex flex-row gap-6">
          <aside className="lg:w-1/4 hidden lg:block">
            <SidebarWrapper />
          </aside>
          <main className="lg:w-3/4 w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
